### ISSUE TITLE
please review this issue on Android 10: Fatal signal 7 (SIGBUS), code 2 (BUS_ADRERR), fault addr 0xf2696000 

### ISSUE THREAD

**Issue by kinshasa** [aliyun/alibabacloud-httpdns-android-sdk#1]
04-19 17:06:08.492  2247 19351 F libc    : Fatal signal 7 (SIGBUS), code 2 (BUS_ADRERR), fault addr 0xf2696000 in tid 19351 (httpdns worker), pid 2247 (igurationcenter)
04-19 17:06:08.897 19392 19392 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-19 17:06:08.897 19392 19392 F DEBUG   : Build fingerprint: 'XPENG/e28/e28:9/PQ3B.190801.002/root04180451:userdebug/release-keys'
04-19 17:06:08.897 19392 19392 F DEBUG   : Revision: '0'
04-19 17:06:08.897 19392 19392 F DEBUG   : ABI: 'arm'
04-19 17:06:08.897 19392 19392 F DEBUG   : pid: 2247, tid: 19351, name: httpdns worker  >>> com.${*******}.configurationcenter <<<
04-19 17:06:08.897 19392 19392 F DEBUG   : signal 7 (SIGBUS), code 2 (BUS_ADRERR), fault addr 0xf2696000
04-19 17:06:08.897 19392 19392 F DEBUG   :     r0  f2696000  r1  d4dea560  r2  d4dea5dc  r3  00000001
04-19 17:06:08.897 19392 19392 F DEBUG   :     r4  ebf227e0  r5  d4dea6c0  r6  00000020  r7  f2696000
04-19 17:06:08.897 19392 19392 F DEBUG   :     r8  d4dea6c0  r9  00000000  r10 ebf23340  r11 00000000
04-19 17:06:08.897 19392 19392 F DEBUG   :     ip  f50216cc  sp  d4dea530  lr  f337637b  pc  f3376a9e
04-19 17:06:09.383 19392 19392 F DEBUG   : 
04-19 17:06:09.383 19392 19392 F DEBUG   : backtrace:
04-19 17:06:09.383 19392 19392 F DEBUG   :     #00 pc 00023a9e  /system/lib/libsqlite.so (walIndexTryHdr+30)
04-19 17:06:09.383 19392 19392 F DEBUG   :     #01 pc 00023377  /system/lib/libsqlite.so (walIndexReadHdr+70)
04-19 17:06:09.383 19392 19392 F DEBUG   :     #02 pc 00022dfb  /system/lib/libsqlite.so (walTryBeginRead+442)
04-19 17:06:09.383 19392 19392 F DEBUG   :     #03 pc 00027e11  /system/lib/libsqlite.so (sqlite3PagerSharedLock+120)
04-19 17:06:09.383 19392 19392 F DEBUG   :     #04 pc 0000c83b  /system/lib/libsqlite.so (sqlite3BtreeBeginTrans+622)
04-19 17:06:09.383 19392 19392 F DEBUG   :     #05 pc 000309bf  /system/lib/libsqlite.so (sqlite3VdbeExec+3598)
04-19 17:06:09.383 19392 19392 F DEBUG   :     #06 pc 0000f645  /system/lib/libsqlite.so (sqlite3_step+484)
04-19 17:06:09.383 19392 19392 F DEBUG   :     #07 pc 000965e9  /system/lib/libandroid_runtime.so (android::nativeExecute(_JNIEnv*, _jclass*, long long, long long)+8)
04-19 17:06:09.383 19392 19392 F DEBUG   :     #08 pc 003acf49  /system/framework/arm/boot-framework.oat (offset 0x3aa000) (android.content.res.AssetManager.nativeThemeCopy [DEDUPED]+120)
04-19 17:06:09.383 19392 19392 F DEBUG   :     #09 pc 00031feb  /dev/ashmem/dalvik-jit-code-cache (deleted) (android.database.sqlite.SQLiteConnection.execute+210)
04-19 17:06:09.383 19392 19392 F DEBUG   :     #10 pc 0006c625  /dev/ashmem/dalvik-jit-code-cache (deleted) (android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration+148)
04-19 17:06:09.383 19392 19392 F DEBUG   :     #11 pc 0006e7e9  /dev/ashmem/dalvik-jit-code-cache (deleted) (android.database.sqlite.SQLiteConnection.open+216)
04-19 17:06:09.383 19392 19392 F DEBUG   :     #12 pc 00417f75  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
04-19 17:06:09.384 19392 19392 F DEBUG   :     #13 pc 003f159f  /system/lib/libart.so (art_quick_invoke_stub+226)
04-19 17:06:09.384 19392 19392 F DEBUG   :     #14 pc 000a1031  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+136)
04-19 17:06:09.384 19392 19392 F DEBUG   :     #15 pc 001e8995  /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+232)
04-19 17:06:09.384 19392 19392 F DEBUG   :     #16 pc 001e3671  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+776)
04-19 17:06:09.384 19392 19392 F DEBUG   :     #17 pc 003ed059  /system/lib/libart.so (MterpInvokeDirect+196)
04-19 17:06:09.384 19392 19392 F DEBUG   :     #18 pc 0040ae14  /system/lib/libart.so (ExecuteMterpImpl+14484)
04-19 17:06:09.384 19392 19392 F DEBUG   :     #19 pc 0043f424  /system/framework/boot-framework.vdex (android.database.sqlite.SQLiteConnection.open+10)
04-19 17:06:09.384 19392 19392 F DEBUG   :     #20 pc 001c7fe9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.4175568579+352)
04-19 17:06:09.384 19392 19392 F DEBUG   :     #21 pc 001cc8b7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
04-19 17:06:09.384 19392 19392 F DEBUG   :     #22 pc 001e365b  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
04-19 17:06:09.384 19392 19392 F DEBUG   :     #23 pc 003ed1a3  /system/lib/libart.so (MterpInvokeStatic+130)
04-19 17:06:09.384 19392 19392 F DEBUG   :     #24 pc 0040ae94  /system/lib/libart.so (ExecuteMterpImpl+14612)
04-19 17:06:09.384 19392 19392 F DEBUG   :     #25 pc 005951b4  /system/framework/boot-framework.vdex (android.database.sqlite.SQLiteConnectionPool.openConnectionLocked+12)
04-19 17:06:09.387 19392 19392 F DEBUG   :     #26 pc 001c7fe9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.4175568579+352)
04-19 17:06:09.387 19392 19392 F DEBUG   :     #27 pc 001cc8b7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
04-19 17:06:09.387 19392 19392 F DEBUG   :     #28 pc 001e365b  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
04-19 17:06:09.387 19392 19392 F DEBUG   :     #29 pc 003ed059  /system/lib/libart.so (MterpInvokeDirect+196)
04-19 17:06:09.387 19392 19392 F DEBUG   :     #30 pc 0040ae14  /system/lib/libart.so (ExecuteMterpImpl+14484)
04-19 17:06:09.387 19392 19392 F DEBUG   :     #31 pc 0043ef9a  /system/framework/boot-framework.vdex (android.database.sqlite.SQLiteConnectionPool.open+6)
04-19 17:06:09.387 19392 19392 F DEBUG   :     #32 pc 001c7fe9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.4175568579+352)
04-19 17:06:09.387 19392 19392 F DEBUG   :     #33 pc 001cc8b7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
04-19 17:06:09.387 19392 19392 F DEBUG   :     #34 pc 001e365b  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
04-19 17:06:09.387 19392 19392 F DEBUG   :     #35 pc 003ed059  /system/lib/libart.so (MterpInvokeDirect+196)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #36 pc 0040ae14  /system/lib/libart.so (ExecuteMterpImpl+14484)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #37 pc 0043ea78  /system/framework/boot-framework.vdex (android.database.sqlite.SQLiteConnectionPool.open+14)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #38 pc 001c7fe9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.4175568579+352)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #39 pc 001cc8b7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #40 pc 001e365b  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #41 pc 003ed1a3  /system/lib/libart.so (MterpInvokeStatic+130)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #42 pc 0040ae94  /system/lib/libart.so (ExecuteMterpImpl+14612)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #43 pc 00442178  /system/framework/boot-framework.vdex (android.database.sqlite.SQLiteDatabase.openInner+12)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #44 pc 001c7fe9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.4175568579+352)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #45 pc 001cc8b7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #46 pc 001e365b  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #47 pc 003ed059  /system/lib/libart.so (MterpInvokeDirect+196)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #48 pc 0040ae14  /system/lib/libart.so (ExecuteMterpImpl+14484)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #49 pc 004420e6  /system/framework/boot-framework.vdex (android.database.sqlite.SQLiteDatabase.open)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #50 pc 001c7fe9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.4175568579+352)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #51 pc 001cc8b7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #52 pc 001e365b  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #53 pc 003ed059  /system/lib/libart.so (MterpInvokeDirect+196)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #54 pc 0040ae14  /system/lib/libart.so (ExecuteMterpImpl+14484)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #55 pc 0044114a  /system/framework/boot-framework.vdex (android.database.sqlite.SQLiteDatabase.openDatabase+98)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #56 pc 001c7fe9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.4175568579+352)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #57 pc 001cc8b7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
04-19 17:06:09.388 19392 19392 F DEBUG   :     #58 pc 001e365b  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #59 pc 003ed1a3  /system/lib/libart.so (MterpInvokeStatic+130)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #60 pc 0040ae94  /system/lib/libart.so (ExecuteMterpImpl+14612)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #61 pc 0059668c  /system/framework/boot-framework.vdex (android.database.sqlite.SQLiteDatabase.openDatabase+8)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #62 pc 001c7fe9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.4175568579+352)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #63 pc 001cc8b7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #64 pc 001e365b  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #65 pc 003ed1a3  /system/lib/libart.so (MterpInvokeStatic+130)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #66 pc 0040ae94  /system/lib/libart.so (ExecuteMterpImpl+14612)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #67 pc 0044251e  /system/framework/boot-framework.vdex (android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked+166)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #68 pc 001c7fe9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.4175568579+352)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #69 pc 001cc8b7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #70 pc 001e365b  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #71 pc 003ed059  /system/lib/libart.so (MterpInvokeDirect+196)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #72 pc 0040ae14  /system/lib/libart.so (ExecuteMterpImpl+14484)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #73 pc 004427ee  /system/framework/boot-framework.vdex (android.database.sqlite.SQLiteOpenHelper.getReadableDatabase+4)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #74 pc 001c7fe9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.4175568579+352)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #75 pc 001cc8b7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #76 pc 001e365b  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #77 pc 003ec1c7  /system/lib/libart.so (MterpInvokeVirtual+442)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #78 pc 0040ad14  /system/lib/libart.so (ExecuteMterpImpl+14228)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #79 pc 0026ed12  /data/dalvik-cache/arm/system@app@xp_ConfigurationCenter@xp_ConfigurationCenter.apk@classes.vdex (com.alibaba.sdk.android.httpdns.b.d.a+98)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #80 pc 001c7fe9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.4175568579+352)
04-19 17:06:09.389 19392 19392 F DEBUG   :     #81 pc 001cc8b7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #82 pc 001e365b  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #83 pc 003ec1c7  /system/lib/libart.so (MterpInvokeVirtual+442)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #84 pc 0040ad14  /system/lib/libart.so (ExecuteMterpImpl+14228)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #85 pc 0026f03a  /data/dalvik-cache/arm/system@app@xp_ConfigurationCenter@xp_ConfigurationCenter.apk@classes.vdex (com.alibaba.sdk.android.httpdns.b.d.b+6)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #86 pc 001c7fe9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.4175568579+352)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #87 pc 001cc8b7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #88 pc 001e365b  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #89 pc 003ec1c7  /system/lib/libart.so (MterpInvokeVirtual+442)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #90 pc 0040ad14  /system/lib/libart.so (ExecuteMterpImpl+14228)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #91 pc 0026e57c  /data/dalvik-cache/arm/system@app@xp_ConfigurationCenter@xp_ConfigurationCenter.apk@classes.vdex (com.alibaba.sdk.android.httpdns.b.a.b+12)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #92 pc 001c7fe9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.4175568579+352)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #93 pc 001cc8b7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #94 pc 001e365b  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #95 pc 003ecd95  /system/lib/libart.so (MterpInvokeInterface+1020)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #96 pc 0040af14  /system/lib/libart.so (ExecuteMterpImpl+14740)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #97 pc 0026e696  /data/dalvik-cache/arm/system@app@xp_ConfigurationCenter@xp_ConfigurationCenter.apk@classes.vdex (com.alibaba.sdk.android.httpdns.b.b.b+10)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #98 pc 001c7fe9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.4175568579+352)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #99 pc 001cc8b7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #100 pc 001e365b  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #101 pc 003ed1a3  /system/lib/libart.so (MterpInvokeStatic+130)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #102 pc 0040ae94  /system/lib/libart.so (ExecuteMterpImpl+14612)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #103 pc 00270656  /data/dalvik-cache/arm/system@app@xp_ConfigurationCenter@xp_ConfigurationCenter.apk@classes.vdex (com.alibaba.sdk.android.httpdns.d.b+134)
04-19 17:06:09.390 19392 19392 F DEBUG   :     #104 pc 001c7fe9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.4175568579+352)
04-19 17:06:09.391 19392 19392 F DEBUG   :     #105 pc 001cc8b7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
04-19 17:06:09.391 19392 19392 F DEBUG   :     #106 pc 001e365b  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
04-19 17:06:09.391 19392 19392 F DEBUG   :     #107 pc 003ed059  /system/lib/libart.so (MterpInvokeDirect+196)
04-19 17:06:09.391 19392 19392 F DEBUG   :     #108 pc 0040ae14  /system/lib/libart.so (ExecuteMterpImpl+14484)
04-19 17:06:09.391 19392 19392 F DEBUG   :     #109 pc 002704e4  /data/dalvik-cache/arm/system@app@xp_ConfigurationCenter@xp_ConfigurationCenter.apk@classes.vdex (com.alibaba.sdk.android.httpdns.d.a)
04-19 17:06:09.391 19392 19392 F DEBUG   :     #110 pc 001c7fe9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.4175568579+352)
04-19 17:06:09.391 19392 19392 F DEBUG   :     #111 pc 001cc8b7  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
04-19 17:06:09.391 19392 19392 F DEBUG   :     #112 pc 001e365b  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+754)
04-19 17:06:09.391 19392 19392 F DEBUG   :     #113 pc 003ed1a3  /system/lib/libart.so (MterpInvokeStatic+130)
04-19 17:06:09.391 19392 19392 F DEBUG   :     #114 pc 0040ae94  /system/lib/libart.so (ExecuteMterpImpl+14612)
04-19 17:06:09.391 19392 19392 F DEBUG   :     #115 pc 0026f954  /data/dalvik-cache/arm/system@app@xp_ConfigurationCenter@xp_ConfigurationCenter.apk@classes.vdex (com.alibaba.sdk.android.httpdns.d$2.run+4)
04-19 17:06:09.391 19392 19392 F DEBUG   :     #116 pc 001c7fe9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.4175568579+352)
04-19 17:06:09.391 19392 19392 F DEBUG   :     #117 pc 001cc803  /system/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+82)

**Comment by new-xd** [comment]
I can not reproduce this on Android 10. We have changed our code about sqlite on 2.1.0. Please try it

**Comment by new-xd** [comment]
Please upgrade to 2.1.1
And if this issue exists, reopen it
