### ISSUE TITLE
Why does this library rely on multiple libraries?

### ISSUE THREAD

**Issue by Haoxiqiang** [aliyun/alibabacloud-httpdns-android-sdk#4]
when the app uses the httpdns library.  Google Play was rejected by the message.

![FEEB5D89-40A1-4346-976E-E03F4257AD1B](https://user-images.githubusercontent.com/3881604/146765811-7e5b786b-47c3-4542-8ad0-de4255154b58.png)

And I have to build a prune version by myself: https://github.com/Haoxiqiang/alibabacloud-httpdns-android-sdk
 As the third service, the shit bucket is a terrible design.

btw.the httpdns is based fee services, at least you should show the complete declaration and license.

**Comment by Haoxiqiang** [comment]
![image](https://user-images.githubusercontent.com/3881604/146766694-a5352e07-c781-41c6-af72-98b0e759b511.png)
After one hour work.
all deps which exclude the beacon is unnecessary.

**Comment by Haoxiqiang** [comment]
![image](https://user-images.githubusercontent.com/3881604/146767945-bc0aee9c-524f-4a71-872a-84ae12648258.png)
That's the uncertain behavior libs.

**Comment by new-xd** [comment]
2.2.1 should fix the issue google reported.

Other libraries provide basic feature for all aliyun's SDK. They can disable httpdns when something goes wrong. 

You can change the code as you wish.
